"""
Hello World schemas

This module contains Pydantic models for hello world messages:
- HelloRequest: Input validation for creating messages
- HelloResponse: API response format
- HelloMessage: Internal database model
"""

from datetime import datetime

from pydantic import BaseModel, Field, field_validator


class HelloRequest(BaseModel):
    """
    Request schema for creating a hello message

    Attributes:
        message: The message content (1-500 characters)
    """

    message: str = Field(
        ...,
        min_length=1,
        max_length=500,
        description="The message content",
        examples=["Hello, World!", "Bonjour le monde!"],
    )

    @field_validator("message")
    @classmethod
    def validate_message(cls, v: str) -> str:
        """
        Validate and clean the message

        Args:
            v: The message to validate

        Returns:
            The cleaned message

        Raises:
            ValueError: If message is empty or only whitespace
        """
        if not v or not v.strip():
            raise ValueError("Message cannot be empty")
        return v.strip()


class HelloResponse(BaseModel):
    """
    Response schema for a hello message

    Attributes:
        id: Unique identifier of the message
        message: The message content
        created_at: ISO 8601 timestamp of creation
    """

    id: int = Field(..., description="Unique message identifier")
    message: str = Field(..., description="Message content")
    created_at: str = Field(..., description="Creation timestamp (ISO 8601)")

    model_config = {
        "from_attributes": True,
        "json_schema_extra": {
            "examples": [
                {"id": 1, "message": "Hello, World!", "created_at": "2024-12-05T10:30:00Z"}
            ]
        },
    }


class HelloMessage(BaseModel):
    """
    Internal database model for hello messages

    This model represents the database schema and is used internally
    by repositories and services. It maps directly to the Supabase table.

    Attributes:
        id: Primary key (auto-generated)
        message: Message content
        created_at: Timestamp (auto-generated by database)
    """

    id: int | None = Field(None, description="Auto-generated ID")
    message: str = Field(..., min_length=1, max_length=500)
    created_at: datetime | None = Field(None, description="Auto-generated timestamp")

    model_config = {"from_attributes": True}
