"""Remove sensor_id from Machine

Revision ID: 8cb0e1e91d06
Revises: 41d246b6c30c
Create Date: 2026-01-09 18:37:59.268569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cb0e1e91d06'
down_revision: Union[str, Sequence[str], None] = '41d246b6c30c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('machines', 'sensor_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('machines', sa.Column('sensor_id', sa.UUID(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
