"""Add machine_id to SetHistory

Revision ID: a586b6b7cae2
Revises: de49815799c1
Create Date: 2026-01-10 00:02:18.755435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a586b6b7cae2'
down_revision: Union[str, Sequence[str], None] = 'de49815799c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sets_history', sa.Column('machine_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sets_history', 'machine_id')
    # ### end Alembic commands ###
