"""Add knowledge_items table and vector extension

Revision ID: de49815799c1
Revises: 8cb0e1e91d06
Create Date: 2026-01-09 21:46:53.127420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector

# revision identifiers, used by Alembic.
revision: str = 'de49815799c1'
down_revision: Union[str, Sequence[str], None] = '8cb0e1e91d06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Ensure vector extension exists
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('content_text', sa.String(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(768), nullable=False),
    sa.Column('metadata_info', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_items'))
    )
    op.create_index(op.f('ix_knowledge_items_source_type'), 'knowledge_items', ['source_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_items_source_type'), table_name='knowledge_items')
    op.drop_table('knowledge_items')
    # ### end Alembic commands ###
