"""Initial db models

Revision ID: ff1938b24453
Revises: 
Create Date: 2026-01-09 17:59:18.691017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ff1938b24453'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('muscle_group', sa.String(), nullable=False),
    sa.Column('machine_type_id', sa.String(), nullable=True),
    sa.Column('alternatives', sa.ARRAY(sa.UUID()), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exercises'))
    )
    op.create_index(op.f('ix_exercises_name'), 'exercises', ['name'], unique=False)
    op.create_table('machines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('machine_type_id', sa.String(), nullable=False),
    sa.Column('sensor_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('zone', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_machines'))
    )
    op.create_index(op.f('ix_machines_machine_type_id'), 'machines', ['machine_type_id'], unique=False)
    op.create_table('programs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('goal', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_programs'))
    )
    op.create_index(op.f('ix_programs_user_id'), 'programs', ['user_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('program_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('exercises_plan', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], name=op.f('fk_sessions_program_id_programs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions'))
    )
    op.create_table('sessions_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_xp', sa.Integer(), nullable=False),
    sa.Column('feedback_notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_sessions_history_session_id_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions_history'))
    )
    op.create_index(op.f('ix_sessions_history_user_id'), 'sessions_history', ['user_id'], unique=False)
    op.create_table('sets_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_history_id', sa.UUID(), nullable=False),
    sa.Column('exercise_id', sa.UUID(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('reps_count', sa.Integer(), nullable=False),
    sa.Column('rpe', sa.Integer(), nullable=True),
    sa.Column('sensor_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], name=op.f('fk_sets_history_exercise_id_exercises')),
    sa.ForeignKeyConstraint(['session_history_id'], ['sessions_history.id'], name=op.f('fk_sets_history_session_history_id_sessions_history')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sets_history'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sets_history')
    op.drop_index(op.f('ix_sessions_history_user_id'), table_name='sessions_history')
    op.drop_table('sessions_history')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_programs_user_id'), table_name='programs')
    op.drop_table('programs')
    op.drop_index(op.f('ix_machines_machine_type_id'), table_name='machines')
    op.drop_table('machines')
    op.drop_index(op.f('ix_exercises_name'), table_name='exercises')
    op.drop_table('exercises')
    # ### end Alembic commands ###
